[config]
schemaVersion = "0.0.1"

[package]
namespace = "CelesteSols"
name = "CelesteSols"
versionNumber = "0.2.0"
description = "Celeste Movement"
websiteUrl = "https://github.com/asd9176506911298/NineSols-CelesteSols"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "1.2.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
